#!/usr/bin/env bash
cd /admscripts/cis/Assessor-CLI/reports
ping -c 5 8.8.8.8 > ping_$(hostname)_$(date +%Y%m%d).txt
netstat -noa > services_$(hostname)_$(date +%Y%m%d).txt && systemctl --type=service >> services_$(hostname)_$(date +%Y%m%d).txt
cat  /etc/redhat-release > redhat-release_$(hostname)